# -*- coding: utf-8 -*-
# Generated by Django 1.9c1 on 2015-11-25 00:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20151125_0018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='location',
            field=models.IntegerField(null=True),
        ),
    ]
